services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app_container
    ports:
      - "1100:1100"
    environment:
      - PORT=1100
      # Пример, если нужны переменные окружения
      # - ENV=development
      # - SECRET_KEY=placeholder_secret
    volumes:
      # Пример: подключаем локальную директорию /app, если хотим видеть изменения в реальном времени
      # - .:/app
      - ./storage:/app/storage
    restart: unless-stopped