services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: felv
    ports:
      - "1100:1100"
    volumes:
      # Пример: подключаем локальную директорию /app, если хотим видеть изменения в реальном времени
      # - .:/app
      - ./storage:/app/storage
    restart: unless-stopped